Sprint1
ClevertecFrontendLab/sprint1-Oliolixinfree pull request #1
Opened 2023-01-30 22:54 UTC by Oliolixinfree

2023-01-30 22:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675119482/content-window.png)

2023-01-31 06:29 UTC, Gaurrus requested changes
убери весь закомментированный код)

2023-01-31 06:29 UTC, Gaurrus commented on src/pages/book-page/book-page.tsx
> +      <BookDetails />{' '}
что за пробел?)

2023-01-31 06:29 UTC, Gaurrus commented on .eslintrc.js
> +  extends: [require.resolve('arui-presets-lint/eslint'), 'plugin:react/jsx-runtime'],
![image](https://user-images.githubusercontent.com/85307211/215683123-8638681d-b267-4665-9040-e20ad0bbb3d3.png)

2023-01-31 06:29 UTC, Gaurrus commented on src/ui/button/button.module.scss
> +  font-size: 12px;
![image](https://user-images.githubusercontent.com/85307211/215683587-7845d084-9475-4816-b129-bbc7a49af528.png)
на всех кнопках посмотри шрифты, здесь точно не соответствует, сверься с макетом

2023-01-31 17:21 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Oliolixinfree/1675185704/content-window.png)

2023-02-01 14:42 UTC, Ivan6813 approved these changes

2023-02-01 14:44 UTC, Gaurrus approved these changes

2023-02-01 14:55 UTC, merged